project:
  type: website
  output-dir: docs

website:
  title: "Waranya (Kae) Ratirotjanakul"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/wrat0001-rgb
        aria-label: GitHub
        target: _blank
      - icon: linkedin
        href: https://www.linkedin.com/in/waranya-ratirotjanakul-a09b74175/
        aria-label: LinkedIn
        target: _blank
format:
  html:
    theme: lux
    toc: true
    css: styles.css



